### ISSUE TITLE
Doesn't change profiles for keypad

### ISSUE THREAD

**Issue by MF-JEWM** [ShayBox/Wooting-Profile-Switcher#12] opened 2023-10-12 03:24 UTC
Not sure if this is known as I think the keypads are just now starting to arrive for people in the mail.

I also don't know if there is even proper support for choosing which of the two devices would be controlled considering that version of Wootility is in beta still.

Figured I would just try to make you aware of this though in case you weren't 100% sure whether the program would or wouldn't work properly.

So to clarify, I have a Wooting 60HE and a UwU keypad plugged in. The program can change the profile for my Wooting 60HE, but not my UwU keypad. I even have the profile names matching the ones on my keypad instead of my 60HE and it still won't do anything in relation to the keypad.

**Comment by ShayBox** [comment] 2023-10-12 03:28
Try unplugging your keyboard and see, the RGB SDK as far as I know never supported more than one keyboard, I know Wootility Beta has support now but afaik RGB SDK hasn't been updated. And the new Wootility Beta introduces a new RGB Effects system that this program is incompatible with right now.

**Comment by ShayBox** [comment] 2023-10-12 03:33
Actually never mind, unplugging your keyboard wouldn't work because the RGB SDK doesn't have the UwU device PID. I don't think Wootility uses the RGB SDK so until that gets updated and I can figure out any command changes needed to use the new RGB Effects I can't support the UwU or Wootility Beta, but it is planned.

**Comment by ShayBox** [comment] 2023-10-12 13:07
Oh nice, I always forget about branches. I'll try to update it and publish a release.

**Comment by ShayBox** [comment] 2023-10-12 14:16
I haven't tested it with the new Wootility yet, I'd bet the JSON config has more data that my program isn't expecting yet, but that's a guess.

I think I'm going to add a device index to rules, each device can have its own rule; otherwise, I would have to keep a list of a list of rules and have a device drop down like Wootility, which is less optimal, but what are your thoughts on how to interface with multiple devices?

**Comment by ShayBox** [comment] 2023-10-12 14:23
I wish I could use the Analog SDK which is in Rust now but I have to use the RGB SDK which is still in C/C++ but I forked and updated a bindgen wrapper. I think the functionality already exists in RGB SDK but I never used it because it was unlikely anyone would have two keyboards plugged in.

**Comment by ShayBox** [comment] 2023-10-13 02:52
I wouldn't mind having a brightness slider for rules, but I believe it's part of the RGB matrix for each key, though Wootility has a per-key and a global slider per-profile so you can change that and it will apply with WPS.

Artemis can detect active process and swap lighting profiles so that's probably a better option, but that doesn't save to the device like Wootility.

**Comment by ShayBox** [comment] 2023-10-13 12:00
The latest release adds multi-device support, still not beta and RGB effects, that's waiting for Wootility to be released stable. let me know if there's any bugs with the update.

**Comment by ShayBox** [comment] 2023-10-15 20:36
I released a pre-release that should support everything, but you have to **uninstall** Wootility and install Wootility Beta

https://github.com/ShayBox/Wooting-Profile-Switcher/releases/tag/2.3.0

**Comment by BrutalCSEjziponken** [comment] 2023-10-19 17:31
Not sure if this belongs in a separate topic or not. But mine does not switch either. Using latest beta wootility and Switcher.
I cant even pick profile in the app for some reason.

[](https://i.imgur.com/r1GchHt.png)

**Comment by BrutalCSEjziponken** [comment] 2023-10-19 18:34
> I released a pre-release that should support everything, but you have to **uninstall** Wootility and install Wootility Beta
> 
> https://github.com/ShayBox/Wooting-Profile-Switcher/releases/tag/2.3.0

Not sure if this belongs in a separate topic or not. But mine does not switch either with my TWO HE keyboard. Using latest beta Wootility and Switcher.

I can't even pick profile in the app for some reason. My config does not have any device info in it (even if I delete and restart the app).

Wootility v4.6.4-beta
Firmware: v2.7.0-beta.2
Wooting-Profile-Switcher 2.3.0

Edit:
Also tried with the new updates
Wootility v4.6.5-beta
Firmware v2.7.0-beta.3

https://i.imgur.com/r1GchHt.png

**Comment by ShayBox** [comment] 2023-10-19 18:47
Make sure you have the stable wootilitt uninstalled and delete the wootility-lekker folder in appdata roaming, and delete the WPS config in appdata roaming too. It should pull device info from beta first time you open WPS as long as wootility isn't open.

**Comment by BrutalCSEjziponken** [comment] 2023-10-19 19:32
> wootility-lekker folder in appdata roaming

Thanks, seems the issue was the "wootility-lekker folder in appdata roaming". :)

**Comment by ShayBox** [comment] 2023-10-19 21:17
It seems the fallback rule had priority over the other rule(s), what position was it in before deleting it? I thought I made new rules insert from the top to keep the fallback at the bottom and tested it (top/highest to bottom/lowest priority)

**Comment by BrutalCSEjziponken** [comment] 2023-10-19 22:48
> It seems the fallback rule had priority over the other rule(s), what position was it in before deleting it? I thought I made new rules insert from the top to keep the fallback at the bottom and tested it (top/highest to bottom/lowest priority)

I think it was on the bottom.

**Comment by ShayBox** [comment] 2023-10-20 00:31
I'll do some testing, I also remembered that I forgot to add buttons to move the rules around and an indicator for active rule.

**Comment by ShayBox** [comment] 2023-10-20 16:00
I found the bug, it was checking for properties then rules instead of rules then properties. so it would match the first rule that had a matching app name, then bin name, bin path, and win name. That will be fixed in the next update.

**Comment by ShayBox** [comment] 2023-10-20 18:34
Try this version https://github.com/ShayBox/Wooting-Profile-Switcher/releases/tag/2.3.1

**Comment by BrutalCSEjziponken** [comment] 2023-10-20 19:01
> Try this version https://github.com/ShayBox/Wooting-Profile-Switcher/releases/tag/2.3.1

Thank you, I can confirm that this new one works for me. :)

**Closed** 2024-03-26 11:33 UTC
